apiVersion: batch/v1
kind: CronJob
metadata:
  name: mydotnetapp1-cronjob
spec:
  schedule: "*/4 * * * *"  # Run every 4 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mahesagrimba/mydotnetapp1
            image: mahesagrimba/mydotnetapp1:latest
          restartPolicy: OnFailure
